trigger:
  - main
  - web-workflow-test


schedules:
- cron: '30 21 * * *'
  displayName: 'Nightly test run - 03:00 AM IST'
  branches:
    include:
      - main
  always: true
- cron: '30 22 * * *'
  displayName: 'Nightly test run - 04:00 AM IST'
  branches:
    include:
      - main
  always: true
- cron: '30 23 * * *'
  displayName: 'Nightly test run - 05:00 AM IST'
  branches:
    include:
      - main
  always: true

variables:
- group: WebAutomationVariables

pool:
  vmImage: 'windows-latest'

steps:

- task: UseNode@1
  inputs:
    version: '24.x'
  displayName: 'Set Up Node.js'

- script: npm ci
  displayName: 'Install Dependencies'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

- script: mkdir reports
  displayName: 'Create Reports Directory'
  continueOnError: true

- script: npm run test:web
  displayName: 'Run Cucumber Tests'
  env:
    WEB_BASE_URL: $(WEB_BASE_URL)
    MFA_BASE_URL: $(MFA_BASE_URL)
    GITHUB_USER: $(GITHUB_USER)
    GITHUB_PASS: $(GITHUB_PASS)
    GITHUB_MFA_SECRET: $(GITHUB_MFA_SECRET)
    BROWSER: $(BROWSER)
    WEB_PARALLEL_WORKERS: $(WEB_PARALLEL_WORKERS)
- task: PublishTestResults@2
  displayName: 'Publish JUnit Test Results'
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'reports/cucumber.xml'
    failTaskOnFailedTests: false
    testRunTitle: 'Playwright Cucumber Tests'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: reports
    artifact: CucumberReport
  condition: always()

- script: |
    npm run allure:generate

    echo ===== ALLURE REPORT =====
    dir allure-report
  displayName: 'Generate Allure Report'
  condition: always()

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'allure-report'
    artifact: 'AllureReport'
  condition: always()

- task: PowerShell@2
  displayName: 'Generate Email Report'
  condition: always()
  inputs:
    targetType: 'inline'
    script: |
      npx ts-node reporting/generateEmailReport.ts

- task: PowerShell@2
  displayName: 'Send Email Report'
  condition: always()
  inputs:
    targetType: 'inline'
    script: |

      $html = Get-Content "reports/email-report.html" -Raw

      # TEMP TEST
      $html = $html.Substring(0,1000)

      $payload = @{
          subject = "ANZ Automation Report"
          htmlBody = $html
      } | ConvertTo-Json -Compress

      Invoke-RestMethod `
        -Uri "$(POWER_AUTOMATE_URL)" `
        -Method POST `
        -ContentType "application/json" `
        -Body $payload `
        -ErrorAction Stop

      Write-Host "Email sent successfully"